---
- hosts: vpn

  vars:
    server_addr: 10.8.0.1
    client_addr: 10.8.0.2
    keyfile: static.key
    keepalive: "10 60"
    compression: true

  tasks:
  - include: tasks/base.yml
  - include: tasks/vpn.yml

  handlers:
  - include: handlers/vpn.yml
